// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const result: string;
export const error: string;
export const loader: string;
export const rotation: string;
