// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const trigger: string;
export const item: string;
export const arrow: string;
export const content: string;
